//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrupoComponente.Web.ServiceReferenceTestGP {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceTestGP.IServiceTest")]
    public interface IServiceTest {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTest/GetUsers", ReplyAction="http://tempuri.org/IServiceTest/GetUsersResponse")]
        GrupoComponente.Data.Entidades.Response<GrupoComponente.Data.Entidades.User> GetUsers(System.Nullable<long> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTest/GetUsers", ReplyAction="http://tempuri.org/IServiceTest/GetUsersResponse")]
        System.Threading.Tasks.Task<GrupoComponente.Data.Entidades.Response<GrupoComponente.Data.Entidades.User>> GetUsersAsync(System.Nullable<long> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTest/SetUser", ReplyAction="http://tempuri.org/IServiceTest/SetUserResponse")]
        GrupoComponente.Data.Entidades.Response<GrupoComponente.Data.Entidades.User> SetUser(GrupoComponente.Data.Entidades.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTest/SetUser", ReplyAction="http://tempuri.org/IServiceTest/SetUserResponse")]
        System.Threading.Tasks.Task<GrupoComponente.Data.Entidades.Response<GrupoComponente.Data.Entidades.User>> SetUserAsync(GrupoComponente.Data.Entidades.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTest/DelUser", ReplyAction="http://tempuri.org/IServiceTest/DelUserResponse")]
        GrupoComponente.Data.Entidades.Response<GrupoComponente.Data.Entidades.User> DelUser(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTest/DelUser", ReplyAction="http://tempuri.org/IServiceTest/DelUserResponse")]
        System.Threading.Tasks.Task<GrupoComponente.Data.Entidades.Response<GrupoComponente.Data.Entidades.User>> DelUserAsync(long id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceTestChannel : GrupoComponente.Web.ServiceReferenceTestGP.IServiceTest, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceTestClient : System.ServiceModel.ClientBase<GrupoComponente.Web.ServiceReferenceTestGP.IServiceTest>, GrupoComponente.Web.ServiceReferenceTestGP.IServiceTest {
        
        public ServiceTestClient() {
        }
        
        public ServiceTestClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceTestClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceTestClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceTestClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GrupoComponente.Data.Entidades.Response<GrupoComponente.Data.Entidades.User> GetUsers(System.Nullable<long> id) {
            return base.Channel.GetUsers(id);
        }
        
        public System.Threading.Tasks.Task<GrupoComponente.Data.Entidades.Response<GrupoComponente.Data.Entidades.User>> GetUsersAsync(System.Nullable<long> id) {
            return base.Channel.GetUsersAsync(id);
        }
        
        public GrupoComponente.Data.Entidades.Response<GrupoComponente.Data.Entidades.User> SetUser(GrupoComponente.Data.Entidades.User user) {
            return base.Channel.SetUser(user);
        }
        
        public System.Threading.Tasks.Task<GrupoComponente.Data.Entidades.Response<GrupoComponente.Data.Entidades.User>> SetUserAsync(GrupoComponente.Data.Entidades.User user) {
            return base.Channel.SetUserAsync(user);
        }
        
        public GrupoComponente.Data.Entidades.Response<GrupoComponente.Data.Entidades.User> DelUser(long id) {
            return base.Channel.DelUser(id);
        }
        
        public System.Threading.Tasks.Task<GrupoComponente.Data.Entidades.Response<GrupoComponente.Data.Entidades.User>> DelUserAsync(long id) {
            return base.Channel.DelUserAsync(id);
        }
    }
}
